// GENERATED by tools/make-presets.mjs -- do not edit by hand.
// Station and daypart names with their broadcast times. No audio is bundled;
// the listener imports their own files and they are matched into these slots.
import type { Station } from './types';

export const STATION_PRESETS: Station[] = [
  {
    "id": "st-blueprint",
    "name": "Blueprint",
    "albumKey": "blueprint",
    "frequency": 90.5,
    "programs": [
      {
        "id": "st-blueprint-p1",
        "name": "Alba",
        "startHour": 5.383333,
        "trackIds": []
      },
      {
        "id": "st-blueprint-p2",
        "name": "Midi",
        "startHour": 11.7,
        "trackIds": []
      },
      {
        "id": "st-blueprint-p3",
        "name": "Terra",
        "startHour": 16.666667,
        "trackIds": []
      },
      {
        "id": "st-blueprint-p4",
        "name": "Glomo",
        "startHour": 22.85,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-breathwork",
    "name": "Breathwork",
    "albumKey": "breathwork",
    "frequency": 92.7,
    "programs": [
      {
        "id": "st-breathwork-p1",
        "name": "Andante",
        "startHour": 4.8,
        "trackIds": []
      },
      {
        "id": "st-breathwork-p2",
        "name": "Sleigh Bells",
        "startHour": 10.133333,
        "trackIds": []
      },
      {
        "id": "st-breathwork-p3",
        "name": "Vox Humana",
        "startHour": 22.25,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-fourthspace",
    "name": "Fourth Space",
    "albumKey": "fourthspace",
    "frequency": 95.3,
    "programs": [
      {
        "id": "st-fourthspace-p1",
        "name": "Dawn",
        "startHour": 2.833333,
        "trackIds": []
      },
      {
        "id": "st-fourthspace-p2",
        "name": "Dusk",
        "startHour": 17.683333,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-journeybeat",
    "name": "Journey Beat",
    "albumKey": "journeybeat",
    "frequency": 98.1,
    "programs": [
      {
        "id": "st-journeybeat-p1",
        "name": "Bounce",
        "startHour": 4.35,
        "trackIds": []
      },
      {
        "id": "st-journeybeat-p2",
        "name": "Whistler",
        "startHour": 9.516667,
        "trackIds": []
      },
      {
        "id": "st-journeybeat-p3",
        "name": "Journey Beat",
        "startHour": 13.333333,
        "trackIds": []
      },
      {
        "id": "st-journeybeat-p4",
        "name": "Holy Beat",
        "startHour": 19.55,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-lobby",
    "name": "Lobby",
    "albumKey": "lobby",
    "frequency": 100.9,
    "programs": [
      {
        "id": "st-lobby-p1",
        "name": "Motif",
        "startHour": 0,
        "trackIds": []
      },
      {
        "id": "st-lobby-p2",
        "name": "Leitmotif",
        "startHour": 7.2,
        "trackIds": []
      },
      {
        "id": "st-lobby-p3",
        "name": "Refrain",
        "startHour": 14.683333,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-mallets",
    "name": "Mallets",
    "albumKey": "mallets",
    "frequency": 103.5,
    "programs": [
      {
        "id": "st-mallets-p1",
        "name": "Phase i",
        "startHour": 3.933333,
        "trackIds": []
      },
      {
        "id": "st-mallets-p2",
        "name": "Phase ii",
        "startHour": 10.15,
        "trackIds": []
      },
      {
        "id": "st-mallets-p3",
        "name": "Phase iii",
        "startHour": 20.15,
        "trackIds": []
      }
    ]
  },
  {
    "id": "st-underground",
    "name": "Underground",
    "albumKey": "underground",
    "frequency": 106.7,
    "programs": [
      {
        "id": "st-underground-p1",
        "name": "Antemma",
        "startHour": 1.183333,
        "trackIds": []
      },
      {
        "id": "st-underground-p2",
        "name": "Suns",
        "startHour": 7.016667,
        "trackIds": []
      },
      {
        "id": "st-underground-p3",
        "name": "Flashes",
        "startHour": 10.75,
        "trackIds": []
      },
      {
        "id": "st-underground-p4",
        "name": "Yuhyuh",
        "startHour": 15.883333,
        "trackIds": []
      },
      {
        "id": "st-underground-p5",
        "name": "Electr",
        "startHour": 20.966667,
        "trackIds": []
      }
    ]
  }
];

/** Albums with no time-stamped tracks, so they aren't stations. */
export const NON_STATION_ALBUMS: string[] = [
  "B-Sides"
];
