// Reads ./music and writes src/core/presets.ts: the dial, its dayparts, and the
// path to the file each one plays. Only names, times, durations and paths are
// emitted -- no audio is bundled. The host serves ./music alongside the app.
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { albumKey, minutesToHour, parseTrackName } from '../src/core/naming.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const musicDir = join(root, 'music');
const cachePath = join(root, 'node_modules/.duration-cache.json');

const cache = existsSync(cachePath) ? JSON.parse(readFileSync(cachePath, 'utf8')) : {};
let probed = 0;

/** Durations are baked in so the schedule is right before any audio loads. */
function durationOf(absolutePath) {
  const key = absolutePath.slice(root.length);
  if (cache[key] != null) return cache[key];
  try {
    const out = execFileSync('ffprobe', [
      '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', absolutePath,
    ], { encoding: 'utf8' });
    cache[key] = Math.round(Number(out.trim()) * 1000) / 1000;
  } catch {
    // No ffprobe, or an unreadable file: the app probes it in the browser instead.
    cache[key] = 0;
  }
  probed++;
  return cache[key];
}

const AUDIO = /\.(flac|mp3|m4a|ogg|opus|wav|aac)$/i;

const albums = existsSync(musicDir)
  ? readdirSync(musicDir).filter((name) => statSync(join(musicDir, name)).isDirectory()).sort()
  : [];

const catalog = [];

const stations = albums.map((dir) => {
  const files = readdirSync(join(musicDir, dir)).filter((f) => AUDIO.test(f)).sort();
  const name = parseTrackName(dir).album ?? dir;
  const key = albumKey(name);

  const dayparts = files
    .map((file) => {
      const parsed = parseTrackName(file);
      if (parsed.timeOfDayMinutes === null) return null;
      const path = `music/${dir}/${file}`;
      catalog.push({
        id: path,
        name: parsed.title,
        duration: durationOf(join(musicDir, dir, file)),
        src: path,
        album: name,
        timeOfDayMinutes: parsed.timeOfDayMinutes,
      });
      return { title: parsed.title, minutes: parsed.timeOfDayMinutes, path };
    })
    .filter(Boolean)
    .sort((a, b) => a.minutes - b.minutes);

  return {
    id: `st-${key}`,
    name,
    albumKey: key,
    channel: 0,
    programs: dayparts.map((d, n) => ({
      id: `st-${key}-p${n + 1}`,
      name: d.title,
      startHour: Number(minutesToHour(d.minutes).toFixed(6)),
      trackIds: [d.path],
    })),
  };
});

// Numbered along the dial, densely, so albums without a schedule don't leave gaps.
const withPrograms = stations.filter((s) => s.programs.length > 0);
withPrograms.forEach((s, i) => { s.channel = i + 1; });
const skipped = stations.filter((s) => s.programs.length === 0);

const used = new Set(withPrograms.flatMap((s) => s.programs.flatMap((p) => p.trackIds)));
const tracks = catalog.filter((t) => used.has(t.id));

if (probed) writeFileSync(cachePath, JSON.stringify(cache));

writeFileSync(join(root, 'src/core/presets.ts'), `// GENERATED by tools/make-presets.mjs -- do not edit by hand.
// The dial, its dayparts, and the file each one plays. No audio is bundled:
// these paths are served by whoever hosts the app, from ./music next to it.
import type { Station, Track } from './types';

export const STATION_PRESETS: Station[] = ${JSON.stringify(withPrograms, null, 2)};

export const TRACK_CATALOG: Track[] = ${JSON.stringify(tracks, null, 2)};

/** Albums with no time-stamped tracks, so they aren't stations. */
export const NON_STATION_ALBUMS: string[] = ${JSON.stringify(skipped.map((s) => s.name), null, 2)};
`);

console.log(`${withPrograms.length} stations, ${tracks.length} tracks`);
for (const s of withPrograms) {
  console.log(`  ${s.channel}  ${s.name}: ${s.programs.length} dayparts`);
}
const missing = tracks.filter((t) => t.duration <= 0);
if (missing.length) console.log(`WARNING: no duration for ${missing.length} track(s); the browser will probe them`);
if (skipped.length) console.log(`skipped (no timestamps): ${skipped.map((s) => s.name).join(', ')}`);
