// Reads ./music and writes src/core/presets.ts: the dial, its dayparts, and the
// path to the file each one plays. Only names, times, durations and paths are
// emitted -- no audio is bundled. The host serves ./music alongside the app.
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { albumKey, minutesToHour, parseTrackName } from '../src/core/naming.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const musicDir = join(root, 'music');
const cachePath = join(root, 'node_modules/.duration-cache.json');

const cache = existsSync(cachePath) ? JSON.parse(readFileSync(cachePath, 'utf8')) : {};
let probed = 0;

/** Durations are baked in so the schedule is right before any audio loads. */
function durationOf(absolutePath) {
  const key = absolutePath.slice(root.length);
  if (cache[key] != null) return cache[key];
  try {
    const out = execFileSync('ffprobe', [
      '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', absolutePath,
    ], { encoding: 'utf8' });
    cache[key] = Math.round(Number(out.trim()) * 1000) / 1000;
  } catch {
    // No ffprobe, or an unreadable file: the app probes it in the browser instead.
    cache[key] = 0;
  }
  probed++;
  return cache[key];
}

const AUDIO = /\.(flac|mp3|m4a|ogg|opus|wav|aac)$/i;

const albums = existsSync(musicDir)
  ? readdirSync(musicDir).filter((name) => statSync(join(musicDir, name)).isDirectory()).sort()
  : [];

if (albums.length === 0) console.log('no album folders under ./music');

const catalog = [];

function addTrack(dir, file, album, timeOfDayMinutes, title) {
  const path = `music/${dir}/${file}`;
  catalog.push({
    id: path,
    name: title,
    duration: durationOf(join(musicDir, dir, file)),
    src: path,
    album,
    timeOfDayMinutes,
  });
  return path;
}

const scheduled = [];
const skipped = [];

for (const dir of albums) {
  const files = readdirSync(join(musicDir, dir)).filter((f) => AUDIO.test(f)).sort();
  if (files.length === 0) continue;

  const name = parseTrackName(dir).album ?? dir;
  const key = albumKey(name);
  const parsed = files.map((file) => ({ file, ...parseTrackName(file) }));
  const stamped = parsed.filter((p) => p.timeOfDayMinutes !== null);

  if (stamped.length > 0) {
    // Time-stamped albums are dayparted: one looping track per time of day.
    const dayparts = stamped
      .map((p) => ({ ...p, path: addTrack(dir, p.file, name, p.timeOfDayMinutes, p.title) }))
      .sort((a, b) => a.timeOfDayMinutes - b.timeOfDayMinutes);
    scheduled.push({
      id: `st-${key}`,
      name,
      albumKey: key,
      channel: 0,
      programs: dayparts.map((d, n) => ({
        id: `st-${key}-p${n + 1}`,
        name: d.title,
        startHour: Number(minutesToHour(d.timeOfDayMinutes).toFixed(6)),
        trackIds: [d.path],
      })),
    });
  } else {
    // An album with no times on it isn't a schedule, so it gets no channel.
    // The scheduler still supports shuffled programs if one is wanted later.
    skipped.push(name);
  }
}

const stations = scheduled;
stations.forEach((s, i) => { s.channel = i + 1; });

const used = new Set(stations.flatMap((s) => s.programs.flatMap((p) => p.trackIds)));
const tracks = catalog.filter((t) => used.has(t.id));

if (probed) writeFileSync(cachePath, JSON.stringify(cache));

writeFileSync(join(root, 'src/core/presets.ts'), `// GENERATED by tools/make-presets.mjs -- do not edit by hand.
// The dial and the file each daypart plays. No audio is bundled: these paths
// are served by whoever hosts the app, from ./music next to it.
import type { Station, Track } from './types';

export const STATION_PRESETS: Station[] = ${JSON.stringify(stations, null, 2)};

export const TRACK_CATALOG: Track[] = ${JSON.stringify(tracks, null, 2)};
`);

console.log(`${stations.length} channels, ${tracks.length} tracks`);
for (const s of stations) {
  console.log(`  ${s.channel}  ${s.name}: ${s.programs.length} dayparts`);
}
if (skipped.length) console.log(`no times, so no channel: ${skipped.join(', ')}`);
const missing = tracks.filter((t) => t.duration <= 0);
if (missing.length) console.log(`WARNING: no duration for ${missing.length} track(s); the browser will probe them`);
